package com.bill.greendaotest.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bill.greendaotest.db.StudentEntity;
import com.bill.greendaotest.db.TeacherEntity;

import com.bill.greendaotest.greendao.StudentEntityDao;
import com.bill.greendaotest.greendao.TeacherEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;

    private final StudentEntityDao studentEntityDao;
    private final TeacherEntityDao teacherEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);

        registerDao(StudentEntity.class, studentEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
    }
    
    public void clear() {
        studentEntityDaoConfig.clearIdentityScope();
        teacherEntityDaoConfig.clearIdentityScope();
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

}
